# Generated by Django 4.0.5 on 2022-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_education_description_alter_education_todate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='degree',
        ),
        migrations.AlterField(
            model_name='education',
            name='fromDate',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='education',
            name='toDate',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
