# Generated by Django 4.0.5 on 2022-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='fromDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='toDate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
