# Generated by Django 4.0.5 on 2022-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_education_fromdate_alter_education_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='toDate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
