import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Navbar from '../components/Navbar/index'
import AboutMe from '../components/AboutMe/index'
import Experience from '../components/Experience/index'
import Projects from '../components/Projects/index'
import Testimonials from '../components/Testimonials/index'
import ContactMe from '../components/ContactMe/index'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Soham Bhoir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.Navbar}>
          <Navbar />
        </section>

        <section className={styles.AboutMe}>
          <AboutMe />
        </section>

        <section className={styles.Experience}>
          <Experience />
        </section>

        <section className={styles.Projects}>
          <Projects />
        </section>

        <section className={styles.Testimonials}>
          <Testimonials/>
        </section>

        <section className={styles.ContactMe}>
          <ContactMe />
        </section>
      </main>

      <footer className={styles.footer}>
        <section className={styles.footerTitle}>
          <h4>Made With ❤️ and ⚡ by Soham Bhoir</h4>
        </section>
      </footer>
    </div>
  )
}
