# Generated by Django 4.0.4 on 2022-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('avatar', models.ImageField(upload_to='testimonials/')),
                ('profession', models.CharField(max_length=60)),
            ],
        ),
    ]
