# Generated by Django 4.0.4 on 2022-05-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_aboutme_education_experience_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.education'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='portfolio.experience'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.projects'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='socialMediaLinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialMediaLinks', to='portfolio.socialmedialinks'),
        ),
    ]
