# Generated by Django 4.0.4 on 2022-05-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutme_education_aboutme_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
