# Generated by Django 4.0.4 on 2022-05-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='education',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='socialMediaLinks',
        ),
        migrations.AddField(
            model_name='education',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='socialMediaLinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
    ]
