# Generated by Django 4.0.4 on 2022-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_aboutme_education_remove_aboutme_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
